import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import SideBar from "./sidebar/page";

const geistSans = Geist({
 variable: "--font-geist-sans",
 subsets: ["latin"],
});
const geistMono = Geist_Mono({
 variable: "--font-geist-mono",
 subsets: ["latin"],
});

export const metadata: Metadata = {
 title: "Create Next App",
 description: "Generated by create next app",
};

export default function RootLayout({
 children,
}: Readonly<{
 children: React.ReactNode;
}>) {
 return (
  <html lang="en">
   <body className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
    <div className="flex pt-16">
     <SideBar />
     <main className="ml-[150px] flex-1 p-15 bg-white min-h-screen">
      {children}
     </main>
    </div>
   </body>
  </html>
 );
}
